"""
Material Presets Management
Pre-configured settings for realistic, RTS game, animation, stylized, and sci-fi materials.
"""

import json
from typing import Dict, Any
from .pbr_engine import PBRMapSettings


DEFAULT_PRESETS: Dict[str, Dict[str, Any]] = {
    # --- REALISTIC / GENERAL MATERIALS ---
    "Piedra / Roca (Stone / Rock)": {
        "height_contrast": 1.4,
        "height_brightness": 0.0,
        "height_blur": 0.8,
        "height_invert": False,
        "height_source": "luminance",
        "normal_strength": 3.2,
        "normal_filter": "scharr",
        "normal_flip_y": False,
        "normal_flip_x": False,
        "normal_detail": 0.6,
        "normal_blur": 0.0,
        "roughness_base": 0.85,
        "roughness_contrast": 1.2,
        "roughness_invert": False,
        "roughness_min": 0.5,
        "roughness_max": 0.98,
        "roughness_high_freq": 0.4,
        "metallic_mode": "manual_constant",
        "metallic_base_val": 0.0,
        "metallic_threshold": 0.7,
        "metallic_tolerance": 0.2,
        "ao_intensity": 1.8,
        "ao_radius": 10,
        "ao_contrast": 1.4,
    },
    "Madera Rustica (Rough Wood)": {
        "height_contrast": 1.3,
        "height_brightness": -0.05,
        "height_blur": 1.0,
        "height_invert": False,
        "height_source": "luminance",
        "normal_strength": 2.2,
        "normal_filter": "scharr",
        "normal_flip_y": False,
        "normal_flip_x": False,
        "normal_detail": 0.45,
        "normal_blur": 0.0,
        "roughness_base": 0.68,
        "roughness_contrast": 1.1,
        "roughness_invert": False,
        "roughness_min": 0.35,
        "roughness_max": 0.9,
        "roughness_high_freq": 0.35,
        "metallic_mode": "manual_constant",
        "metallic_base_val": 0.0,
        "metallic_threshold": 0.8,
        "metallic_tolerance": 0.2,
        "ao_intensity": 1.4,
        "ao_radius": 8,
        "ao_contrast": 1.2,
    },
    "Madera Pulida (Polished Wood)": {
        "height_contrast": 0.7,
        "height_brightness": 0.0,
        "height_blur": 1.5,
        "height_invert": False,
        "height_source": "luminance",
        "normal_strength": 0.9,
        "normal_filter": "sobel",
        "normal_flip_y": False,
        "normal_flip_x": False,
        "normal_detail": 0.15,
        "normal_blur": 0.2,
        "roughness_base": 0.22,
        "roughness_contrast": 0.7,
        "roughness_invert": False,
        "roughness_min": 0.1,
        "roughness_max": 0.45,
        "roughness_high_freq": 0.1,
        "metallic_mode": "manual_constant",
        "metallic_base_val": 0.0,
        "metallic_threshold": 0.9,
        "metallic_tolerance": 0.1,
        "ao_intensity": 0.8,
        "ao_radius": 6,
        "ao_contrast": 1.0,
    },
    "Metal Pulido / Cromo (Polished Metal)": {
        "height_contrast": 0.5,
        "height_brightness": 0.0,
        "height_blur": 1.0,
        "height_invert": False,
        "height_source": "luminance",
        "normal_strength": 0.8,
        "normal_filter": "sobel",
        "normal_flip_y": False,
        "normal_flip_x": False,
        "normal_detail": 0.2,
        "normal_blur": 0.0,
        "roughness_base": 0.18,
        "roughness_contrast": 0.6,
        "roughness_invert": False,
        "roughness_min": 0.05,
        "roughness_max": 0.35,
        "roughness_high_freq": 0.15,
        "metallic_mode": "manual_constant",
        "metallic_base_val": 1.0,
        "metallic_threshold": 0.5,
        "metallic_tolerance": 0.2,
        "ao_intensity": 0.6,
        "ao_radius": 4,
        "ao_contrast": 1.1,
    },
    "Metal Oxidado (Rusted Metal)": {
        "height_contrast": 1.5,
        "height_brightness": 0.0,
        "height_blur": 0.6,
        "height_invert": False,
        "height_source": "luminance",
        "normal_strength": 2.8,
        "normal_filter": "scharr",
        "normal_flip_y": False,
        "normal_flip_x": False,
        "normal_detail": 0.7,
        "normal_blur": 0.0,
        "roughness_base": 0.72,
        "roughness_contrast": 1.4,
        "roughness_invert": False,
        "roughness_min": 0.3,
        "roughness_max": 0.95,
        "roughness_high_freq": 0.6,
        "metallic_mode": "threshold",
        "metallic_threshold": 0.65,
        "metallic_tolerance": 0.2,
        "metallic_base_val": 0.5,
        "ao_intensity": 1.9,
        "ao_radius": 9,
        "ao_contrast": 1.5,
    },
    "Concreto / Cemento (Concrete)": {
        "height_contrast": 1.1,
        "height_brightness": 0.0,
        "height_blur": 0.9,
        "height_invert": False,
        "height_source": "luminance",
        "normal_strength": 2.0,
        "normal_filter": "scharr",
        "normal_flip_y": False,
        "normal_flip_x": False,
        "normal_detail": 0.5,
        "normal_blur": 0.0,
        "roughness_base": 0.88,
        "roughness_contrast": 1.0,
        "roughness_invert": False,
        "roughness_min": 0.65,
        "roughness_max": 0.98,
        "roughness_high_freq": 0.45,
        "metallic_mode": "manual_constant",
        "metallic_base_val": 0.0,
        "metallic_threshold": 0.8,
        "metallic_tolerance": 0.2,
        "ao_intensity": 1.6,
        "ao_radius": 8,
        "ao_contrast": 1.3,
    },
    "Azulejos / Baldosas (Tiles / Ceramic)": {
        "height_contrast": 1.6,
        "height_brightness": 0.0,
        "height_blur": 0.5,
        "height_invert": False,
        "height_source": "luminance",
        "normal_strength": 2.5,
        "normal_filter": "scharr",
        "normal_flip_y": False,
        "normal_flip_x": False,
        "normal_detail": 0.25,
        "normal_blur": 0.0,
        "roughness_base": 0.25,
        "roughness_contrast": 1.5,
        "roughness_invert": False,
        "roughness_min": 0.1,
        "roughness_max": 0.8,
        "roughness_high_freq": 0.2,
        "metallic_mode": "manual_constant",
        "metallic_base_val": 0.0,
        "metallic_threshold": 0.85,
        "metallic_tolerance": 0.15,
        "ao_intensity": 2.0,
        "ao_radius": 7,
        "ao_contrast": 1.6,
    },
    "Tela / Tejido (Fabric / Cloth)": {
        "height_contrast": 1.0,
        "height_brightness": 0.0,
        "height_blur": 0.3,
        "height_invert": False,
        "height_source": "luminance",
        "normal_strength": 1.6,
        "normal_filter": "scharr",
        "normal_flip_y": False,
        "normal_flip_x": False,
        "normal_detail": 0.8,
        "normal_blur": 0.0,
        "roughness_base": 0.92,
        "roughness_contrast": 0.8,
        "roughness_invert": False,
        "roughness_min": 0.75,
        "roughness_max": 1.0,
        "roughness_high_freq": 0.5,
        "metallic_mode": "manual_constant",
        "metallic_base_val": 0.0,
        "metallic_threshold": 0.9,
        "metallic_tolerance": 0.1,
        "ao_intensity": 1.3,
        "ao_radius": 5,
        "ao_contrast": 1.2,
    },
    "Cuero (Leather)": {
        "height_contrast": 1.3,
        "height_brightness": 0.0,
        "height_blur": 0.7,
        "height_invert": False,
        "height_source": "luminance",
        "normal_strength": 2.0,
        "normal_filter": "scharr",
        "normal_flip_y": False,
        "normal_flip_x": False,
        "normal_detail": 0.55,
        "normal_blur": 0.0,
        "roughness_base": 0.58,
        "roughness_contrast": 1.2,
        "roughness_invert": False,
        "roughness_min": 0.3,
        "roughness_max": 0.85,
        "roughness_high_freq": 0.4,
        "metallic_mode": "manual_constant",
        "metallic_base_val": 0.0,
        "metallic_threshold": 0.8,
        "metallic_tolerance": 0.2,
        "ao_intensity": 1.5,
        "ao_radius": 6,
        "ao_contrast": 1.3,
    },
    "Plastico / Caucho (Plastic / Rubber)": {
        "height_contrast": 0.8,
        "height_brightness": 0.0,
        "height_blur": 1.2,
        "height_invert": False,
        "height_source": "luminance",
        "normal_strength": 1.2,
        "normal_filter": "sobel",
        "normal_flip_y": False,
        "normal_flip_x": False,
        "normal_detail": 0.2,
        "normal_blur": 0.1,
        "roughness_base": 0.45,
        "roughness_contrast": 0.8,
        "roughness_invert": False,
        "roughness_min": 0.2,
        "roughness_max": 0.7,
        "roughness_high_freq": 0.15,
        "metallic_mode": "manual_constant",
        "metallic_base_val": 0.0,
        "metallic_threshold": 0.8,
        "metallic_tolerance": 0.2,
        "ao_intensity": 1.0,
        "ao_radius": 6,
        "ao_contrast": 1.1,
    },

    # --- RTS & STRATEGY GAMES ---
    "RTS - Terreno / Mapa Aereo (Readability Terrain)": {
        "height_contrast": 1.5,
        "height_brightness": 0.0,
        "height_blur": 1.4,
        "height_invert": False,
        "height_source": "luminance",
        "normal_strength": 2.6,
        "normal_filter": "sobel",
        "normal_flip_y": False,
        "normal_flip_x": False,
        "normal_detail": 0.1,
        "normal_blur": 0.4,
        "roughness_base": 0.82,
        "roughness_contrast": 1.0,
        "roughness_invert": False,
        "roughness_min": 0.6,
        "roughness_max": 0.95,
        "roughness_high_freq": 0.1,
        "metallic_mode": "manual_constant",
        "metallic_base_val": 0.0,
        "metallic_threshold": 0.8,
        "metallic_tolerance": 0.2,
        "ao_intensity": 2.4,
        "ao_radius": 14,
        "ao_contrast": 1.8,
    },
    "RTS - Edificios y Murallas (Structure Facade)": {
        "height_contrast": 1.6,
        "height_brightness": 0.0,
        "height_blur": 0.8,
        "height_invert": False,
        "height_source": "luminance",
        "normal_strength": 3.0,
        "normal_filter": "scharr",
        "normal_flip_y": False,
        "normal_flip_x": False,
        "normal_detail": 0.2,
        "normal_blur": 0.1,
        "roughness_base": 0.65,
        "roughness_contrast": 1.3,
        "roughness_invert": False,
        "roughness_min": 0.4,
        "roughness_max": 0.9,
        "roughness_high_freq": 0.2,
        "metallic_mode": "threshold",
        "metallic_threshold": 0.75,
        "metallic_tolerance": 0.15,
        "metallic_base_val": 0.0,
        "ao_intensity": 2.2,
        "ao_radius": 12,
        "ao_contrast": 1.6,
    },
    "RTS - Vegetacion / Bosque (Foliage & Canopy)": {
        "height_contrast": 1.2,
        "height_brightness": 0.05,
        "height_blur": 0.5,
        "height_invert": False,
        "height_source": "luminance",
        "normal_strength": 1.8,
        "normal_filter": "sobel",
        "normal_flip_y": False,
        "normal_flip_x": False,
        "normal_detail": 0.3,
        "normal_blur": 0.2,
        "roughness_base": 0.9,
        "roughness_contrast": 0.7,
        "roughness_invert": False,
        "roughness_min": 0.75,
        "roughness_max": 1.0,
        "roughness_high_freq": 0.2,
        "metallic_mode": "manual_constant",
        "metallic_base_val": 0.0,
        "metallic_threshold": 0.9,
        "metallic_tolerance": 0.1,
        "ao_intensity": 2.6,
        "ao_radius": 10,
        "ao_contrast": 1.7,
    },

    # --- ANIMATION & STYLIZED ---
    "Animacion - Estilizado / Cartoon (Smooth Bevels)": {
        "height_contrast": 1.1,
        "height_brightness": 0.0,
        "height_blur": 2.2,
        "height_invert": False,
        "height_source": "luminance",
        "normal_strength": 1.5,
        "normal_filter": "simple",
        "normal_flip_y": False,
        "normal_flip_x": False,
        "normal_detail": 0.0,
        "normal_blur": 0.6,
        "roughness_base": 0.38,
        "roughness_contrast": 0.6,
        "roughness_invert": False,
        "roughness_min": 0.2,
        "roughness_max": 0.55,
        "roughness_high_freq": 0.0,
        "metallic_mode": "manual_constant",
        "metallic_base_val": 0.0,
        "metallic_threshold": 0.8,
        "metallic_tolerance": 0.2,
        "ao_intensity": 1.1,
        "ao_radius": 8,
        "ao_contrast": 1.2,
    },
    "Animacion - Hand-Painted / Arcane (Painterly)": {
        "height_contrast": 1.3,
        "height_brightness": 0.0,
        "height_blur": 1.2,
        "height_invert": False,
        "height_source": "luminance",
        "normal_strength": 1.7,
        "normal_filter": "sobel",
        "normal_flip_y": False,
        "normal_flip_x": False,
        "normal_detail": 0.25,
        "normal_blur": 0.2,
        "roughness_base": 0.52,
        "roughness_contrast": 1.1,
        "roughness_invert": False,
        "roughness_min": 0.3,
        "roughness_max": 0.8,
        "roughness_high_freq": 0.15,
        "metallic_mode": "threshold",
        "metallic_threshold": 0.7,
        "metallic_tolerance": 0.2,
        "metallic_base_val": 0.2,
        "ao_intensity": 1.6,
        "ao_radius": 9,
        "ao_contrast": 1.4,
    },
    "Animacion - Anime Cel-Shading (Flat & Crisp)": {
        "height_contrast": 0.6,
        "height_brightness": 0.0,
        "height_blur": 2.5,
        "height_invert": False,
        "height_source": "luminance",
        "normal_strength": 0.6,
        "normal_filter": "simple",
        "normal_flip_y": False,
        "normal_flip_x": False,
        "normal_detail": 0.0,
        "normal_blur": 0.8,
        "roughness_base": 0.6,
        "roughness_contrast": 0.4,
        "roughness_invert": False,
        "roughness_min": 0.45,
        "roughness_max": 0.7,
        "roughness_high_freq": 0.0,
        "metallic_mode": "manual_constant",
        "metallic_base_val": 0.0,
        "metallic_threshold": 0.9,
        "metallic_tolerance": 0.1,
        "ao_intensity": 0.7,
        "ao_radius": 5,
        "ao_contrast": 1.0,
    },

    # --- HARD-SURFACE / SCI-FI & MECHA ---
    "Sci-Fi - Paneles de Nave / Hull (Hard Surface)": {
        "height_contrast": 1.8,
        "height_brightness": 0.0,
        "height_blur": 0.4,
        "height_invert": False,
        "height_source": "luminance",
        "normal_strength": 3.4,
        "normal_filter": "scharr",
        "normal_flip_y": False,
        "normal_flip_x": False,
        "normal_detail": 0.4,
        "normal_blur": 0.0,
        "roughness_base": 0.28,
        "roughness_contrast": 1.3,
        "roughness_invert": False,
        "roughness_min": 0.12,
        "roughness_max": 0.65,
        "roughness_high_freq": 0.25,
        "metallic_mode": "manual_constant",
        "metallic_base_val": 0.85,
        "metallic_threshold": 0.5,
        "metallic_tolerance": 0.2,
        "ao_intensity": 2.2,
        "ao_radius": 7,
        "ao_contrast": 1.6,
    },
    "Sci-Fi - Armadura Mech / Polimero (Coated Armor)": {
        "height_contrast": 1.4,
        "height_brightness": 0.0,
        "height_blur": 0.6,
        "height_invert": False,
        "height_source": "luminance",
        "normal_strength": 2.4,
        "normal_filter": "scharr",
        "normal_flip_y": False,
        "normal_flip_x": False,
        "normal_detail": 0.3,
        "normal_blur": 0.0,
        "roughness_base": 0.35,
        "roughness_contrast": 1.0,
        "roughness_invert": False,
        "roughness_min": 0.18,
        "roughness_max": 0.6,
        "roughness_high_freq": 0.2,
        "metallic_mode": "manual_constant",
        "metallic_base_val": 0.3,
        "metallic_threshold": 0.6,
        "metallic_tolerance": 0.2,
        "ao_intensity": 1.8,
        "ao_radius": 6,
        "ao_contrast": 1.4,
    },

    # --- RETRO 3D / LOW-POLY ---
    "Retro 3D / Low-Poly (Sharp & Matte)": {
        "height_contrast": 1.6,
        "height_brightness": 0.0,
        "height_blur": 0.0,
        "height_invert": False,
        "height_source": "luminance",
        "normal_strength": 2.0,
        "normal_filter": "simple",
        "normal_flip_y": False,
        "normal_flip_x": False,
        "normal_detail": 0.0,
        "normal_blur": 0.0,
        "roughness_base": 0.85,
        "roughness_contrast": 0.9,
        "roughness_invert": False,
        "roughness_min": 0.6,
        "roughness_max": 0.95,
        "roughness_high_freq": 0.0,
        "metallic_mode": "manual_constant",
        "metallic_base_val": 0.0,
        "metallic_threshold": 0.8,
        "metallic_tolerance": 0.2,
        "ao_intensity": 1.5,
        "ao_radius": 4,
        "ao_contrast": 1.3,
    }
}


class PresetManager:
    """Handles loading, saving, and applying material presets."""
    
    @staticmethod
    def get_preset_names():
        return list(DEFAULT_PRESETS.keys())

    @staticmethod
    def apply_preset(settings: PBRMapSettings, preset_name: str) -> bool:
        if preset_name in DEFAULT_PRESETS:
            settings.from_dict(DEFAULT_PRESETS[preset_name])
            return True
        return False

    @staticmethod
    def save_custom_preset(settings: PBRMapSettings, file_path: str):
        data = settings.to_dict()
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4)

    @staticmethod
    def load_custom_preset(settings: PBRMapSettings, file_path: str) -> bool:
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            settings.from_dict(data)
            return True
        except Exception:
            return False
